__name__ = "ebt"
__version__ = "2.0.83"
__author__ = "larrabee"
__email__ = "kafatron@gmail.com"
__description__ = "Flexible backup framework"
__long_description__ = "Backup framework with rsync, mysql, libvirt, btrfs, lvm and amazon glacier plugins."
__url__ = "https://github.com/larrabee/ebt"
__license__ = "GPLv3"
